apiVersion: v1
kind: Service
metadata:
  name: "webapp-frontend-service"
  # namespace: {{ .Values.namespace.name }}
spec:
  selector:
    tier: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000