apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-frontend.serviceName" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    tier: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
