apiVersion: v1
kind: Service
metadata:
  name: "webapp-backend-service"
  # namespace: {{ .Values.namespace.name }}
spec:
  selector:
    tier: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http