apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-backend.databaseSecret" . }}
  # namespace: {{ .Values.namespace.name }}
data:
  # Configuration values can be set as key-value properties
  MYSQL_USER: {{ .Values.database.user }}
  MYSQL_PASSWORD: {{ .Values.database.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc}}