apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-backend.s3Secret" . }}
  # namespace: {{ .Values.namespace.name }}
data:
  # Configuration values can be set as key-value properties
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accesskey | b64enc}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretkey | b64enc }}