# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ template "helm-backend.serviceName" . }}
#   # namespace: {{ .Values.namespace.name }}
# spec:
#   selector:
#     tier: backend
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#       name: http
